# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          MSSQL_SA_PASSWORD: NotARea1Passw0rd!
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
          
    defaults:
      run: 
        working-directory: ./MasterMealMind
    env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Initial Catalog=Todos;User Id=sa;Password=NotARea1Passw0rd!;TrustServerCertificate=True"
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: EF Tool inst
      run: dotnet tool install --global dotnet-ef --version 7.0.14
    - name: Apply EF Core Migrations
      run: dotnet ef database update --project ./MasterMealMind.API

    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Test
      run: dotnet test --verbosity normal --no-build --configuration Release
