on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-custom-method:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Show current directory
        run: |
          pwd
          ls -al

      - name: Run custom method
        run: dotnet run --project ./MasterMealMind/MasterMealMind.Web.csproj RunScraper
        env:
          DEFAULTCONNECTION: ${{ secrets.DEFAULTCONNECTION }}
