name: Spell Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install -g cspell

    - name: Spell Check
      run: cspell "**/*.{md,cs}" --config .cspell.json || echo "Spell check completed with issues"

